### ISSUE TITLE
Solana TO-DO List

### ISSUE THREAD

**Issue by hsyndeniz** [craftlabs-tech/rely-wallet#12]

**Comment by hsyndeniz** [comment]
- [ ] SOL transactions
- [ ] SPL Token transsactions
- [ ] NFTs
- [ ] In app web3 browser
- [ ] Staking
- [ ] Solarch.io and other explorers
- [ ] Notiffication using solarch or helius
- [ ] Create NFTs (take a look at compressed NFTs)
- [ ] DeFi
